<?php

/**
 * @file
 * Functions to support theming in the <%= theme_name%> theme.
 */

use Drupal\user\Entity\User;
use Drupal\user\RoleInterface;

/**
 * Implements template_preprocess_page().
 */
function <%= theme_name %>_preprocess_page(&$variables) {
  // Load the library specific for Admin users.
  if (User::load(\Drupal::currentUser()->id())->hasRole(RoleInterface::AUTHENTICATED_ID)) {
    $variables['#attached']['library'][] = '<%= theme_name %>/admin';
  }
}
